### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by lxbarth** [openstreetmap/stateofthemap-2016#1]
@tatsvc - per voice today:
- [x] Say "workshops" in program https://github.com/openstreetmap/stateofthemap-2016/commit/eace9dd262b17b10ec8de565ae9d59ea2fee6ff0
- [x] Add official Code of Conduct
- [x] Update any osm.us email addresses to stateofthemap.org email addresses

**Comment by RobJN** [comment]
Our code of conduct is currently on the wordpress site and will just need copying over. 

There is a short version:
- https://2016.stateofthemap.org/code-of-conduct/

And a long version:
- https://2016.stateofthemap.org/code-of-conduct-anti-harassment-policy/

**Comment by tatsvc** [comment]
>  Update any osm.us email addresses to stateofthemap.org email addresses

`board@stateofthemap.org`? or ?

**Comment by tatsvc** [comment]
@lxbarth @marcu @xivk what needs to happen for this site to be live? 

Right now it lives at http://openstreetmap.github.io/stateofthemap-2016/

I assume we want https://2016.stateofthemap.org/ to go to this site?

**Comment by mikelmaron** [comment]
http://2016.stateofthemap.org/ launched! DNS should propogate by tomorrow

if we want https, need to arrange hosting on another site. closing for now
