### ISSUE TITLE
Summary of Updates, April 15

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/stateofthemap-2016#4]
Summary of updates for @tatsvc.
- [x] **Update sponsors pack** The PDF needs to be updated with changes to exhibitor option [ref](https://github.com/osmbe/sotm2016/issues/48#issuecomment-209179702)
- [x] **link sponsors pack from website** We're going to link the sponsors pack from the website. Still keep emphasis on emailing the team for more info [ref](https://github.com/osmbe/sotm2016/issues/29#issuecomment-208530758)
- [x] **Add sponsors.** We have 3 bronze sponsors, and one supporter. Let's start there, more expected soon. SVGs pending [ref](https://github.com/osmbe/sotm2016/issues/29)
- [x] **add scholarships call**. Post will be out early next week, will update here once link is up. [ref](https://github.com/osmbe/sotm2016/issues/39)
- [x] **Add link to Call for Proposals blog post**. Post will be out early next week, will update here once link is up. [ref](https://github.com/osmbe/sotm2016/issues/11)

**Comment by tatsvc** [comment]
Working on this here https://github.com/openstreetmap/stateofthemap-2016/pull/5

**Comment by althio** [comment]
@tatsvc Is it possible to change exhibitor option also for Supporter level
as per https://github.com/osmbe/sotm2016/issues/48#issuecomment-214656198

I would like to send the updated package to previously contacted potential sponsors.
But I fear the table is a bit awkward at the moment.

**Comment by althio** [comment]
:+1: @tatsvc
